    ; Don't even think of reading this code
    ; It was automatically generated by md5-586.pl
    ; Which is a perl program used to generate the x86 assember for
    ; any of elf, a.out, BSDI, Win32, gaswin (for GNU as on Win32) or Solaris
    ; eric <eay@cryptsoft.com>
    ;
    TITLE   md5-x86-64.asm
.code
md5_block_asm_host_order PROC

; see http://weblogs.asp.net/oldnewthing/archive/2004/01/14/58579.aspx
; All registers must be preserved across the call, except for
;   rax, r10, r9, r8, rdx, rcx, and r11, which are scratch.
;   The first four parameters to a function are passed in r10, r9, r8 and rdx.

    mov [rsp-8],rbx
    mov [rsp-16],rbp

    mov r11d,       r8d

    shl r11d,       6

    add r11,        rdx
    sub r11,        64

    mov eax,        DWORD PTR [rcx]

    mov ebx,        DWORD PTR 4[rcx]
    mov r10d,       DWORD PTR 8[rcx]
    mov r9d,        DWORD PTR 12[rcx]
$L000start:
    ;
    ; R0 section
    mov r8,     r10
    mov rbp,        QWORD PTR [rdx]
    ; R0 0
    xor r8d,        r9d
    and r8d,        ebx
    lea eax,        DWORD PTR 3614090360[ebp*1+eax]
    xor r8d,        r9d
    add eax,        r8d
    mov r8d,        ebx
    rol eax,        7
    shr rbp,32
    ;mov ebp,        DWORD PTR 4[rdx]
    add eax,        ebx
    ; R0 1
    xor r8d,        r10d
    and r8d,        eax
    lea r9d,        DWORD PTR 3905402710[ebp*1+r9d]
    xor r8d,        r10d
    add r9d,        r8d
    mov r8d,        eax
    rol r9d,        12
    mov rbp,        QWORD PTR 8[rdx]
    add r9d,        eax
    ; R0 2
    xor r8d,        ebx
    and r8d,        r9d
    lea r10d,       DWORD PTR 606105819[ebp*1+r10d]
    xor r8d,        ebx
    add r10d,       r8d
    mov r8d,        r9d
    rol r10d,       17
    ;mov ebp,        DWORD PTR 12[rdx]
    shr rbp,32
    add r10d,       r9d
    ; R0 3
    xor r8d,        eax
    and r8d,        r10d
    lea ebx,        DWORD PTR 3250441966[ebp*1+ebx]
    xor r8d,        eax
    add ebx,        r8d
    mov r8d,        r10d
    rol ebx,        22
    mov rbp,        QWORD PTR 16[rdx]
    add ebx,        r10d
    ; R0 4
    xor r8d,        r9d
    and r8d,        ebx
    lea eax,        DWORD PTR 4118548399[ebp*1+eax]
    xor r8d,        r9d
    add eax,        r8d
    mov r8d,        ebx
    rol eax,        7
    ;mov ebp,        DWORD PTR 20[rdx]
    shr rbp,32
    add eax,        ebx
    ; R0 5
    xor r8d,        r10d
    and r8d,        eax
    lea r9d,        DWORD PTR 1200080426[ebp*1+r9d]
    xor r8d,        r10d
    add r9d,        r8d
    mov r8d,        eax
    rol r9d,        12
    mov rbp,        QWORD PTR 24[rdx]
    add r9d,        eax
    ; R0 6
    xor r8d,        ebx
    and r8d,        r9d
    lea r10d,       DWORD PTR 2821735955[ebp*1+r10d]
    xor r8d,        ebx
    add r10d,       r8d
    mov r8d,        r9d
    rol r10d,       17
    ;mov ebp,        DWORD PTR 28[rdx]
    shr rbp,32
    add r10d,       r9d
    ; R0 7
    xor r8d,        eax
    and r8d,        r10d
    lea ebx,        DWORD PTR 4249261313[ebp*1+ebx]
    xor r8d,        eax
    add ebx,        r8d
    mov r8d,        r10d
    rol ebx,        22
    mov rbp,        QWORD PTR 32[rdx]
    add ebx,        r10d
    ; R0 8
    xor r8d,        r9d
    and r8d,        ebx
    lea eax,        DWORD PTR 1770035416[ebp*1+eax]
    xor r8d,        r9d
    add eax,        r8d
    mov r8d,        ebx
    rol eax,        7
    ;mov ebp,        DWORD PTR 36[rdx]
    shr rbp,32
    add eax,        ebx
    ; R0 9
    xor r8d,        r10d
    and r8d,        eax
    lea r9d,        DWORD PTR 2336552879[ebp*1+r9d]
    xor r8d,        r10d
    add r9d,        r8d
    mov r8d,        eax
    rol r9d,        12
    mov rbp,        QWORD PTR 40[rdx]
    add r9d,        eax
    ; R0 10
    xor r8d,        ebx
    and r8d,        r9d
    lea r10d,       DWORD PTR 4294925233[ebp*1+r10d]
    xor r8d,        ebx
    add r10d,       r8d
    mov r8d,        r9d
    rol r10d,       17
    ;mov ebp,        DWORD PTR 44[rdx]
    shr rbp,32
    add r10d,       r9d
    ; R0 11
    xor r8d,        eax
    and r8d,        r10d
    lea ebx,        DWORD PTR 2304563134[ebp*1+ebx]
    xor r8d,        eax
    add ebx,        r8d
    mov r8d,        r10d
    rol ebx,        22
    mov rbp,        QWORD PTR 48[rdx]
    add ebx,        r10d
    ; R0 12
    xor r8d,        r9d
    and r8d,        ebx
    lea eax,        DWORD PTR 1804603682[ebp*1+eax]
    xor r8d,        r9d
    add eax,        r8d
    mov r8d,        ebx
    rol eax,        7
    ;mov ebp,        DWORD PTR 52[rdx]
    shr rbp,32
    add eax,        ebx
    ; R0 13
    xor r8d,        r10d
    and r8d,        eax
    lea r9d,        DWORD PTR 4254626195[ebp*1+r9d]
    xor r8d,        r10d
    add r9d,        r8d
    mov r8d,        eax
    rol r9d,        12
    mov rbp,        QWORD PTR 56[rdx]
    add r9d,        eax
    ; R0 14
    xor r8d,        ebx
    and r8d,        r9d
    lea r10d,       DWORD PTR 2792965006[ebp*1+r10d]
    xor r8d,        ebx
    add r10d,       r8d
    mov r8d,        r9d
    rol r10d,       17
    ;mov ebp,        DWORD PTR 60[rdx]
    shr rbp,32
    add r10d,       r9d
    ; R0 15
    xor r8d,        eax
    and r8d,        r10d
    lea ebx,        DWORD PTR 1236535329[ebp*1+ebx]
    xor r8d,        eax
    add ebx,        r8d
    mov r8d,        r10d
    rol ebx,        22
    mov ebp,        DWORD PTR 4[rdx]
    add ebx,        r10d
    ;
    ; R1 section
    ; R1 16
    lea eax,        DWORD PTR 4129170786[ebp*1+eax]
    xor r8d,        ebx
    and r8d,        r9d
    mov ebp,        DWORD PTR 24[rdx]
    xor r8d,        r10d
    add eax,        r8d
    mov r8d,        ebx
    rol eax,        5
    add eax,        ebx
    ; R1 17
    lea r9d,        DWORD PTR 3225465664[ebp*1+r9d]
    xor r8d,        eax
    and r8d,        r10d
    mov ebp,        DWORD PTR 44[rdx]
    xor r8d,        ebx
    add r9d,        r8d
    mov r8d,        eax
    rol r9d,        9
    add r9d,        eax
    ; R1 18
    lea r10d,       DWORD PTR 643717713[ebp*1+r10d]
    xor r8d,        r9d
    and r8d,        ebx
    mov ebp,        DWORD PTR [rdx]
    xor r8d,        eax
    add r10d,       r8d
    mov r8d,        r9d
    rol r10d,       14
    add r10d,       r9d
    ; R1 19
    lea ebx,        DWORD PTR 3921069994[ebp*1+ebx]
    xor r8d,        r10d
    and r8d,        eax
    mov ebp,        DWORD PTR 20[rdx]
    xor r8d,        r9d
    add ebx,        r8d
    mov r8d,        r10d
    rol ebx,        20
    add ebx,        r10d
    ; R1 20
    lea eax,        DWORD PTR 3593408605[ebp*1+eax]
    xor r8d,        ebx
    and r8d,        r9d
    mov ebp,        DWORD PTR 40[rdx]
    xor r8d,        r10d
    add eax,        r8d
    mov r8d,        ebx
    rol eax,        5
    add eax,        ebx
    ; R1 21
    lea r9d,        DWORD PTR 38016083[ebp*1+r9d]
    xor r8d,        eax
    and r8d,        r10d
    mov ebp,        DWORD PTR 60[rdx]
    xor r8d,        ebx
    add r9d,        r8d
    mov r8d,        eax
    rol r9d,        9
    add r9d,        eax
    ; R1 22
    lea r10d,       DWORD PTR 3634488961[ebp*1+r10d]
    xor r8d,        r9d
    and r8d,        ebx
    mov ebp,        DWORD PTR 16[rdx]
    xor r8d,        eax
    add r10d,       r8d
    mov r8d,        r9d
    rol r10d,       14
    add r10d,       r9d
    ; R1 23
    lea ebx,        DWORD PTR 3889429448[ebp*1+ebx]
    xor r8d,        r10d
    and r8d,        eax
    mov ebp,        DWORD PTR 36[rdx]
    xor r8d,        r9d
    add ebx,        r8d
    mov r8d,        r10d
    rol ebx,        20
    add ebx,        r10d
    ; R1 24
    lea eax,        DWORD PTR 568446438[ebp*1+eax]
    xor r8d,        ebx
    and r8d,        r9d
    mov ebp,        DWORD PTR 56[rdx]
    xor r8d,        r10d
    add eax,        r8d
    mov r8d,        ebx
    rol eax,        5
    add eax,        ebx
    ; R1 25
    lea r9d,        DWORD PTR 3275163606[ebp*1+r9d]
    xor r8d,        eax
    and r8d,        r10d
    mov ebp,        DWORD PTR 12[rdx]
    xor r8d,        ebx
    add r9d,        r8d
    mov r8d,        eax
    rol r9d,        9
    add r9d,        eax
    ; R1 26
    lea r10d,       DWORD PTR 4107603335[ebp*1+r10d]
    xor r8d,        r9d
    and r8d,        ebx
    mov ebp,        DWORD PTR 32[rdx]
    xor r8d,        eax
    add r10d,       r8d
    mov r8d,        r9d
    rol r10d,       14
    add r10d,       r9d
    ; R1 27
    lea ebx,        DWORD PTR 1163531501[ebp*1+ebx]
    xor r8d,        r10d
    and r8d,        eax
    mov ebp,        DWORD PTR 52[rdx]
    xor r8d,        r9d
    add ebx,        r8d
    mov r8d,        r10d
    rol ebx,        20
    add ebx,        r10d
    ; R1 28
    lea eax,        DWORD PTR 2850285829[ebp*1+eax]
    xor r8d,        ebx
    and r8d,        r9d
    mov ebp,        DWORD PTR 8[rdx]
    xor r8d,        r10d
    add eax,        r8d
    mov r8d,        ebx
    rol eax,        5
    add eax,        ebx
    ; R1 29
    lea r9d,        DWORD PTR 4243563512[ebp*1+r9d]
    xor r8d,        eax
    and r8d,        r10d
    mov ebp,        DWORD PTR 28[rdx]
    xor r8d,        ebx
    add r9d,        r8d
    mov r8d,        eax
    rol r9d,        9
    add r9d,        eax
    ; R1 30
    lea r10d,       DWORD PTR 1735328473[ebp*1+r10d]
    xor r8d,        r9d
    and r8d,        ebx
    mov ebp,        DWORD PTR 48[rdx]
    xor r8d,        eax
    add r10d,       r8d
    mov r8d,        r9d
    rol r10d,       14
    add r10d,       r9d
    ; R1 31
    lea ebx,        DWORD PTR 2368359562[ebp*1+ebx]
    xor r8d,        r10d
    and r8d,        eax
    mov ebp,        DWORD PTR 20[rdx]
    xor r8d,        r9d
    add ebx,        r8d
    mov r8d,        r10d
    rol ebx,        20
    add ebx,        r10d
    ;
    ; R2 section
    ; R2 32
    xor r8d,        r9d
    xor r8d,        ebx
    lea eax,        DWORD PTR 4294588738[ebp*1+eax]
    add eax,        r8d
    rol eax,        4
    mov ebp,        DWORD PTR 32[rdx]
    mov r8d,        ebx
    ; R2 33
    lea r9d,        DWORD PTR 2272392833[ebp*1+r9d]
    add eax,        ebx
    xor r8d,        r10d
    xor r8d,        eax
    mov ebp,        DWORD PTR 44[rdx]
    add r9d,        r8d
    mov r8d,        eax
    rol r9d,        11
    add r9d,        eax
    ; R2 34
    xor r8d,        ebx
    xor r8d,        r9d
    lea r10d,       DWORD PTR 1839030562[ebp*1+r10d]
    add r10d,       r8d
    rol r10d,       16
    mov ebp,        DWORD PTR 56[rdx]
    mov r8d,        r9d
    ; R2 35
    lea ebx,        DWORD PTR 4259657740[ebp*1+ebx]
    add r10d,       r9d
    xor r8d,        eax
    xor r8d,        r10d
    mov ebp,        DWORD PTR 4[rdx]
    add ebx,        r8d
    mov r8d,        r10d
    rol ebx,        23
    add ebx,        r10d
    ; R2 36
    xor r8d,        r9d
    xor r8d,        ebx
    lea eax,        DWORD PTR 2763975236[ebp*1+eax]
    add eax,        r8d
    rol eax,        4
    mov ebp,        DWORD PTR 16[rdx]
    mov r8d,        ebx
    ; R2 37
    lea r9d,        DWORD PTR 1272893353[ebp*1+r9d]
    add eax,        ebx
    xor r8d,        r10d
    xor r8d,        eax
    mov ebp,        DWORD PTR 28[rdx]
    add r9d,        r8d
    mov r8d,        eax
    rol r9d,        11
    add r9d,        eax
    ; R2 38
    xor r8d,        ebx
    xor r8d,        r9d
    lea r10d,       DWORD PTR 4139469664[ebp*1+r10d]
    add r10d,       r8d
    rol r10d,       16
    mov ebp,        DWORD PTR 40[rdx]
    mov r8d,        r9d
    ; R2 39
    lea ebx,        DWORD PTR 3200236656[ebp*1+ebx]
    add r10d,       r9d
    xor r8d,        eax
    xor r8d,        r10d
    mov ebp,        DWORD PTR 52[rdx]
    add ebx,        r8d
    mov r8d,        r10d
    rol ebx,        23
    add ebx,        r10d
    ; R2 40
    xor r8d,        r9d
    xor r8d,        ebx
    lea eax,        DWORD PTR 681279174[ebp*1+eax]
    add eax,        r8d
    rol eax,        4
    mov ebp,        DWORD PTR [rdx]
    mov r8d,        ebx
    ; R2 41
    lea r9d,        DWORD PTR 3936430074[ebp*1+r9d]
    add eax,        ebx
    xor r8d,        r10d
    xor r8d,        eax
    mov ebp,        DWORD PTR 12[rdx]
    add r9d,        r8d
    mov r8d,        eax
    rol r9d,        11
    add r9d,        eax
    ; R2 42
    xor r8d,        ebx
    xor r8d,        r9d
    lea r10d,       DWORD PTR 3572445317[ebp*1+r10d]
    add r10d,       r8d
    rol r10d,       16
    mov ebp,        DWORD PTR 24[rdx]
    mov r8d,        r9d
    ; R2 43
    lea ebx,        DWORD PTR 76029189[ebp*1+ebx]
    add r10d,       r9d
    xor r8d,        eax
    xor r8d,        r10d
    mov ebp,        DWORD PTR 36[rdx]
    add ebx,        r8d
    mov r8d,        r10d
    rol ebx,        23
    add ebx,        r10d
    ; R2 44
    xor r8d,        r9d
    xor r8d,        ebx
    lea eax,        DWORD PTR 3654602809[ebp*1+eax]
    add eax,        r8d
    rol eax,        4
    mov ebp,        DWORD PTR 48[rdx]
    mov r8d,        ebx
    ; R2 45
    lea r9d,        DWORD PTR 3873151461[ebp*1+r9d]
    add eax,        ebx
    xor r8d,        r10d
    xor r8d,        eax
    mov ebp,        DWORD PTR 60[rdx]
    add r9d,        r8d
    mov r8d,        eax
    rol r9d,        11
    add r9d,        eax
    ; R2 46
    xor r8d,        ebx
    xor r8d,        r9d
    lea r10d,       DWORD PTR 530742520[ebp*1+r10d]
    add r10d,       r8d
    rol r10d,       16
    mov ebp,        DWORD PTR 8[rdx]
    mov r8d,        r9d
    ; R2 47
    lea ebx,        DWORD PTR 3299628645[ebp*1+ebx]
    add r10d,       r9d
    xor r8d,        eax
    xor r8d,        r10d
    mov ebp,        DWORD PTR [rdx]
    add ebx,        r8d
    mov r8d,        -1
    rol ebx,        23
    add ebx,        r10d
    ;
    ; R3 section
    ; R3 48
    xor r8d,        r9d
    or  r8d,        ebx
    lea eax,        DWORD PTR 4096336452[ebp*1+eax]
    xor r8d,        r10d
    mov ebp,        DWORD PTR 28[rdx]
    add eax,        r8d
    mov r8d,        -1
    rol eax,        6
    xor r8d,        r10d
    add eax,        ebx
    ; R3 49
    or  r8d,        eax
    lea r9d,        DWORD PTR 1126891415[ebp*1+r9d]
    xor r8d,        ebx
    mov ebp,        DWORD PTR 56[rdx]
    add r9d,        r8d
    mov r8d,        -1
    rol r9d,        10
    xor r8d,        ebx
    add r9d,        eax
    ; R3 50
    or  r8d,        r9d
    lea r10d,       DWORD PTR 2878612391[ebp*1+r10d]
    xor r8d,        eax
    mov ebp,        DWORD PTR 20[rdx]
    add r10d,       r8d
    mov r8d,        -1
    rol r10d,       15
    xor r8d,        eax
    add r10d,       r9d
    ; R3 51
    or  r8d,        r10d
    lea ebx,        DWORD PTR 4237533241[ebp*1+ebx]
    xor r8d,        r9d
    mov ebp,        DWORD PTR 48[rdx]
    add ebx,        r8d
    mov r8d,        -1
    rol ebx,        21
    xor r8d,        r9d
    add ebx,        r10d
    ; R3 52
    or  r8d,        ebx
    lea eax,        DWORD PTR 1700485571[ebp*1+eax]
    xor r8d,        r10d
    mov ebp,        DWORD PTR 12[rdx]
    add eax,        r8d
    mov r8d,        -1
    rol eax,        6
    xor r8d,        r10d
    add eax,        ebx
    ; R3 53
    or  r8d,        eax
    lea r9d,        DWORD PTR 2399980690[ebp*1+r9d]
    xor r8d,        ebx
    mov ebp,        DWORD PTR 40[rdx]
    add r9d,        r8d
    mov r8d,        -1
    rol r9d,        10
    xor r8d,        ebx
    add r9d,        eax
    ; R3 54
    or  r8d,        r9d
    lea r10d,       DWORD PTR 4293915773[ebp*1+r10d]
    xor r8d,        eax
    mov ebp,        DWORD PTR 4[rdx]
    add r10d,       r8d
    mov r8d,        -1
    rol r10d,       15
    xor r8d,        eax
    add r10d,       r9d
    ; R3 55
    or  r8d,        r10d
    lea ebx,        DWORD PTR 2240044497[ebp*1+ebx]
    xor r8d,        r9d
    mov ebp,        DWORD PTR 32[rdx]
    add ebx,        r8d
    mov r8d,        -1
    rol ebx,        21
    xor r8d,        r9d
    add ebx,        r10d
    ; R3 56
    or  r8d,        ebx
    lea eax,        DWORD PTR 1873313359[ebp*1+eax]
    xor r8d,        r10d
    mov ebp,        DWORD PTR 60[rdx]
    add eax,        r8d
    mov r8d,        -1
    rol eax,        6
    xor r8d,        r10d
    add eax,        ebx
    ; R3 57
    or  r8d,        eax
    lea r9d,        DWORD PTR 4264355552[ebp*1+r9d]
    xor r8d,        ebx
    mov ebp,        DWORD PTR 24[rdx]
    add r9d,        r8d
    mov r8d,        -1
    rol r9d,        10
    xor r8d,        ebx
    add r9d,        eax
    ; R3 58
    or  r8d,        r9d
    lea r10d,       DWORD PTR 2734768916[ebp*1+r10d]
    xor r8d,        eax
    mov ebp,        DWORD PTR 52[rdx]
    add r10d,       r8d
    mov r8d,        -1
    rol r10d,       15
    xor r8d,        eax
    add r10d,       r9d
    ; R3 59
    or  r8d,        r10d
    lea ebx,        DWORD PTR 1309151649[ebp*1+ebx]
    xor r8d,        r9d
    mov ebp,        DWORD PTR 16[rdx]
    add ebx,        r8d
    mov r8d,        -1
    rol ebx,        21
    xor r8d,        r9d
    add ebx,        r10d
    ; R3 60
    or  r8d,        ebx
    lea eax,        DWORD PTR 4149444226[ebp*1+eax]
    xor r8d,        r10d
    mov ebp,        DWORD PTR 44[rdx]
    add eax,        r8d
    mov r8d,        -1
    rol eax,        6
    xor r8d,        r10d
    add eax,        ebx
    ; R3 61
    or  r8d,        eax
    lea r9d,        DWORD PTR 3174756917[ebp*1+r9d]
    xor r8d,        ebx
    mov ebp,        DWORD PTR 8[rdx]
    add r9d,        r8d
    mov r8d,        -1
    rol r9d,        10
    xor r8d,        ebx
    add r9d,        eax
    ; R3 62
    or  r8d,        r9d
    lea r10d,       DWORD PTR 718787259[ebp*1+r10d]
    xor r8d,        eax
    mov ebp,        DWORD PTR 36[rdx]
    add r10d,       r8d
    mov r8d,        -1
    rol r10d,       15
    xor r8d,        eax
    add r10d,       r9d
    ; R3 63
    or  r8d,        r10d
    lea ebx,        DWORD PTR 3951481745[ebp*1+ebx]
    xor r8d,        r9d

    add ebx,        r8d
    add edx,        64
    rol ebx,        21
    mov r8d,        DWORD PTR [rcx]
    add ebx,        r10d
    add eax,        r8d
    mov r8d,        DWORD PTR 4[rcx]
    add ebx,        r8d
    mov r8d,        DWORD PTR 8[rcx]
    add r10d,       r8d
    mov r8d,        DWORD PTR 12[rcx]
    add r9d,        r8d
    mov DWORD PTR [rcx],eax
    mov DWORD PTR 4[rcx],ebx
    mov r8,     r11
    mov DWORD PTR 8[rcx],r10d
    mov DWORD PTR 12[rcx],r9d
    cmp r8d,        edx
    jae $L000start

    mov rbx,[rsp-8]
    mov rbp,[rsp-16]
    ret
md5_block_asm_host_order ENDP

END
